import OUSVRBLO.GainAdjustedRates
import OUSVRBLO.ProximalLocalInstantiation
import OUSVRBLO.StochasticVarianceRate

namespace OUSVRBLO

noncomputable section

/--
Stable paper-facing exports for the method-oriented ICML theory package.

The declarations in this namespace are thin aliases of the fully checked theorem
stack.  They provide a compact citation surface without introducing any new
mathematical assumptions or weakening the existing claim boundary.
-/
namespace ICMLTheoryPackage

/-- Theorem 1: fallback-safe deterministic finite-horizon Lyapunov budget. -/
theorem fallback_safe_finite_horizon :=
  TrajectoryCertifiedProposalGainSystem.cumulative_budget

/-- Theorem 2: certified accumulated gain tightens the selected trajectory's
same-horizon stationarity/residual certificate. -/
theorem certified_gain_same_iterate :=
  TrajectoryCertifiedProposalGainSystem.exists_joint_certificate_with_gain

/-- Objective-gradient form of the gain-adjusted same-horizon certificate. -/
theorem certified_gain_objective_gradient_same_iterate :=
  TrajectoryCertifiedProposalGainSystem.exists_objective_gradient_joint_certificate_with_gain

/-- Positive accumulated certified gain makes the gain-adjusted numerator
strictly smaller than the safety-only numerator. -/
theorem positive_gain_strictly_tightens :=
  CertifiedGainStepSystem.gainAdjustedRhs_lt_accumulatedRhs_of_positive_gain

/-- Theorem 3: a proximal local-response model instantiates the principal
residual-to-value-gradient error certificate. -/
theorem proximal_response_error_certificate :=
  ProximalRestrictedValueModel.r2

/-- Sequence-level baseline error certificate generated by the same proximal
local-response model. -/
theorem proximal_baseline_sequence_certificate :=
  RestrictedValueProposalData.baseline_error_bound_of_proximal

/-- Theorem 4: exact expectation-level stochastic certified-gain budget. -/
theorem stochastic_expected_finite_horizon :=
  StochasticExpectedGainSystem.cumulative_budget

/-- Gain-adjusted expected average stationarity/residual rate. -/
theorem stochastic_expected_gain_adjusted_average :=
  StochasticExpectedGainSystem.joint_average_bound_with_gain

/-- Manuscript-specialized stochastic rate with explicit
`O(1 / (eta*T) + eta*sigma^2)` dependence. -/
theorem stochastic_variance_rate :=
  StochasticExpectedGainSystem.joint_average_bound_of_variance_only_manuscript

end ICMLTheoryPackage

end

end OUSVRBLO
