import Mathlib

namespace OUSVRBLO

noncomputable section

/--
Sequence-level residual certificate generated by a safe base response and an
accepted online response.

`Rbase` is the residual of the certifiable fallback response, `Ronline` is the
residual of the response actually accepted by the algorithm, and `tau` is the
allowed residual tolerance. The envelope `Q = Rbase + tau` controls both
responses and contracts up to `epsBase + tau`.
-/
structure ResidualSafeguardSystem where
  theta : ℝ
  R : ℕ → ℝ
  Rbase : ℕ → ℝ
  Ronline : ℕ → ℝ
  epsBase : ℕ → ℝ
  tau : ℕ → ℝ
  Rbase_nonneg : ∀ t, 0 ≤ Rbase t
  epsBase_nonneg : ∀ t, 0 ≤ epsBase t
  tau_nonneg : ∀ t, 0 ≤ tau t
  base_contract :
    ∀ t, Rbase t ≤ (1 - theta) * R t + epsBase t
  accepted_safe :
    ∀ t, Ronline t ≤ Rbase t + tau t

/-- Common residual envelope for the base and accepted online responses. -/
def ResidualSafeguardSystem.Q
    (S : ResidualSafeguardSystem) (t : ℕ) : ℝ :=
  S.Rbase t + S.tau t

/-- Total contraction error after including the acceptance tolerance. -/
def ResidualSafeguardSystem.eps
    (S : ResidualSafeguardSystem) (t : ℕ) : ℝ :=
  S.epsBase t + S.tau t

theorem ResidualSafeguardSystem.Q_nonneg
    (S : ResidualSafeguardSystem) (t : ℕ) :
    0 ≤ S.Q t := by
  exact add_nonneg (S.Rbase_nonneg t) (S.tau_nonneg t)

theorem ResidualSafeguardSystem.eps_nonneg
    (S : ResidualSafeguardSystem) (t : ℕ) :
    0 ≤ S.eps t := by
  exact add_nonneg (S.epsBase_nonneg t) (S.tau_nonneg t)

theorem ResidualSafeguardSystem.base_le_envelope
    (S : ResidualSafeguardSystem) (t : ℕ) :
    S.Rbase t ≤ S.Q t := by
  dsimp [ResidualSafeguardSystem.Q]
  linarith [S.tau_nonneg t]

theorem ResidualSafeguardSystem.online_le_envelope
    (S : ResidualSafeguardSystem) (t : ℕ) :
    S.Ronline t ≤ S.Q t := by
  exact S.accepted_safe t

/-- The concrete fallback/acceptance rule closes the abstract contraction
interface used by the main theorem. -/
theorem ResidualSafeguardSystem.envelope_contract
    (S : ResidualSafeguardSystem) (t : ℕ) :
    S.Q t ≤ (1 - S.theta) * S.R t + S.eps t := by
  dsimp [ResidualSafeguardSystem.Q, ResidualSafeguardSystem.eps]
  linarith [S.base_contract t]

end

end OUSVRBLO
