import OUSVRBLO.ValueGradientErrorEmbedding
import OUSVRBLO.TrajectoryCertifiedProposalGain

open BigOperators
open scoped BigOperators InnerProductSpace

namespace OUSVRBLO

noncomputable section

/--
Trajectory-facing theorem in which the inexact-gradient error is defined from
actual value-gradient vectors.

The proposal data contains `gradV`, `gradBase`, and `gradProp`; the
accept/fallback rule selects one approximation, and `Err_t` is defined as
`lambda` times its signed error embedded isometrically into the ambient update
space. Hence the squared error-vector bound is generated by an exact norm
identity.
-/
structure ValueGradientTrajectorySystem
    (E X V : Type*)
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup X] [InnerProductSpace ℝ X]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V] where
  proposal : ValueGradientProposalData V
  driftParameters : DriftParameterization
  errorEmbedding : V →ₗᵢ[ℝ] E
  CR : ℝ
  LP : ℝ
  CR_pos : 0 < CR
  theta_pos : 0 < proposal.theta
  theta_le_one : proposal.theta ≤ 1
  step_size : LP * driftParameters.eta ≤ 1
  small_step : CR * driftParameters.beta ≤ proposal.theta / 4
  Pstar : ℝ
  objective : E → ℝ
  z : ℕ → E
  G : ℕ → E
  projectX : E →L[ℝ] X
  gradR : ℕ → X
  b : ℕ → ℝ
  d : ℕ → ℝ
  R_nonneg : ∀ t, 0 ≤ proposal.R t
  b_nonneg : ∀ t, 0 ≤ b t
  d_nonneg : ∀ t, 0 ≤ d t
  objective_lower : ∀ t, Pstar ≤ objective (z t)
  baseline_error_bound :
    ∀ t, proposal.eBase t ≤ CR * proposal.Rbase t + b t
  update_displacement :
    ∀ t,
      z (t + 1) - z t =
        -driftParameters.eta •
          (G t + proposal.ambientError driftParameters.lam errorEmbedding t)
  objective_smooth_step :
    ∀ t,
      objective (z (t + 1)) ≤ objective (z t)
        + ⟪G t, z (t + 1) - z t⟫_ℝ
        + LP / 2 * ‖z (t + 1) - z t‖ ^ 2
  projectX_contract : ∀ u, ‖projectX u‖ ≤ ‖u‖
  residual_smooth_step_online :
    ∀ t,
      proposal.R (t + 1) ≤ proposal.selector.Ronline t
        + ⟪gradR t, projectX (z (t + 1) - z t)⟫_ℝ
        + driftParameters.LR / 2 *
            ‖projectX (z (t + 1) - z t)‖ ^ 2
        + d t
  residual_grad_sq_bound :
    ∀ t,
      ‖gradR t‖ ^ 2 ≤
        CR * proposal.selector.safeguardSystem.Q t + b t

/-- The selected ambient error vector. -/
def ValueGradientTrajectorySystem.Err
    {E X V : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup X] [InnerProductSpace ℝ X]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    (S : ValueGradientTrajectorySystem E X V) (t : ℕ) : E :=
  S.proposal.ambientError S.driftParameters.lam S.errorEmbedding t

/-- The ambient error norm identity is exposed at the trajectory level. -/
theorem ValueGradientTrajectorySystem.Err_sq
    {E X V : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup X] [InnerProductSpace ℝ X]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    (S : ValueGradientTrajectorySystem E X V) (t : ℕ) :
    ‖S.Err t‖ ^ 2 =
      S.driftParameters.lam ^ 2 * S.proposal.selector.eOnline t := by
  exact S.proposal.ambientError_sq
    S.driftParameters.lam S.errorEmbedding t

/-- Close true value-gradient errors and their isometric ambient embedding into
the trajectory-facing certified proposal theorem. -/
def ValueGradientTrajectorySystem.toTrajectorySystem
    {E X V : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup X] [InnerProductSpace ℝ X]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    (S : ValueGradientTrajectorySystem E X V) :
    TrajectoryCertifiedProposalGainSystem E X where
  proposal := S.proposal.toCertifiedProposalData
  driftParameters := S.driftParameters
  CR := S.CR
  LP := S.LP
  CR_pos := S.CR_pos
  theta_pos := S.theta_pos
  theta_le_one := S.theta_le_one
  step_size := S.step_size
  small_step := S.small_step
  Pstar := S.Pstar
  objective := S.objective
  z := S.z
  G := S.G
  Err := S.Err
  projectX := S.projectX
  gradR := S.gradR
  b := S.b
  d := S.d
  R_nonneg := S.R_nonneg
  b_nonneg := S.b_nonneg
  d_nonneg := S.d_nonneg
  objective_lower := S.objective_lower
  baseline_error_bound := by
    intro t
    simpa [ValueGradientProposalData.toCertifiedProposalData] using
      S.baseline_error_bound t
  error_vector_bound := by
    intro t
    exact S.proposal.ambientError_bound
      S.driftParameters.lam S.errorEmbedding t
  update_displacement := by
    intro t
    simpa [ValueGradientTrajectorySystem.Err] using S.update_displacement t
  objective_smooth_step := S.objective_smooth_step
  projectX_contract := S.projectX_contract
  residual_smooth_step_online := by
    intro t
    simpa [ValueGradientProposalData.selector,
      ValueGradientProposalData.toCertifiedProposalData] using
      S.residual_smooth_step_online t
  residual_grad_sq_bound := by
    intro t
    simpa [ValueGradientProposalData.selector,
      ValueGradientProposalData.toCertifiedProposalData] using
      S.residual_grad_sq_bound t

/-- Public scalar system generated from actual value-gradient vectors. -/
def ValueGradientTrajectorySystem.toCertifiedGainStepSystem
    {E X V : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup X] [InnerProductSpace ℝ X]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    (S : ValueGradientTrajectorySystem E X V) : CertifiedGainStepSystem :=
  S.toTrajectorySystem.toCertifiedGainStepSystem

/-- Exact finite-horizon certified-gain theorem with the error vector defined
from the selected value-gradient approximation. -/
theorem ValueGradientTrajectorySystem.cumulative_budget
    {E X V : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup X] [InnerProductSpace ℝ X]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    (S : ValueGradientTrajectorySystem E X V) (T : ℕ) :
    (S.driftParameters.eta / 4) * SeqSum T (fun t => ‖S.G t‖ ^ 2)
      + S.toCertifiedGainStepSystem.Cgain *
          SeqSum T S.proposal.selector.Gamma
      + (S.driftParameters.eta * S.driftParameters.lam ^ 2 * S.CR / 4) *
          SeqSum T S.proposal.R
      ≤ S.toCertifiedGainStepSystem.Psi 0 - S.Pstar
        + S.toCertifiedGainStepSystem.Ceps *
            SeqSum T S.proposal.selector.safeguardSystem.eps
        + S.toCertifiedGainStepSystem.Cb * SeqSum T S.b
        + S.toCertifiedGainStepSystem.Cd * SeqSum T S.d := by
  exact S.toTrajectorySystem.cumulative_budget T

/-- Simplified finite-horizon theorem using the checked lower gain coefficient. -/
theorem ValueGradientTrajectorySystem.cumulative_budget_simple
    {E X V : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup X] [InnerProductSpace ℝ X]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    (S : ValueGradientTrajectorySystem E X V) (T : ℕ) :
    (S.driftParameters.eta / 4) * SeqSum T (fun t => ‖S.G t‖ ^ 2)
      + (S.driftParameters.eta * S.driftParameters.lam ^ 2 / 2) *
          SeqSum T S.proposal.selector.Gamma
      + (S.driftParameters.eta * S.driftParameters.lam ^ 2 * S.CR / 4) *
          SeqSum T S.proposal.R
      ≤ S.toCertifiedGainStepSystem.Psi 0 - S.Pstar
        + S.toCertifiedGainStepSystem.Ceps *
            SeqSum T S.proposal.selector.safeguardSystem.eps
        + S.toCertifiedGainStepSystem.Cb * SeqSum T S.b
        + S.toCertifiedGainStepSystem.Cd * SeqSum T S.d := by
  exact S.toTrajectorySystem.cumulative_budget_simple T

end

end OUSVRBLO
